/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedPlataformaRouteImport } from './routes/_authenticated/plataforma'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAvisosRouteImport } from './routes/_authenticated/admin.avisos'
import { Route as AuthenticatedAdminConversacionesRouteImport } from './routes/_authenticated/admin.conversaciones'
import { Route as AuthenticatedAdminDocumentosRouteImport } from './routes/_authenticated/admin.documentos'
import { Route as AuthenticatedAdminExpensasRouteImport } from './routes/_authenticated/admin.expensas'
import { Route as AuthenticatedAdminPersonasRouteImport } from './routes/_authenticated/admin.personas'
import { Route as AuthenticatedAdminProveedoresRouteImport } from './routes/_authenticated/admin.proveedores'
import { Route as AuthenticatedAdminReclamosRouteImport } from './routes/_authenticated/admin.reclamos'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAsambleasRouteImport } from './routes/_authenticated/app.asambleas'
import { Route as AuthenticatedAppAsistenteRouteImport } from './routes/_authenticated/app.asistente'
import { Route as AuthenticatedAppAvisosRouteImport } from './routes/_authenticated/app.avisos'
import { Route as AuthenticatedAppContactoRouteImport } from './routes/_authenticated/app.contacto'
import { Route as AuthenticatedAppDocumentosRouteImport } from './routes/_authenticated/app.documentos'
import { Route as AuthenticatedAppExpensasRouteImport } from './routes/_authenticated/app.expensas'
import { Route as AuthenticatedAppMudanzasRouteImport } from './routes/_authenticated/app.mudanzas'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppReclamosRouteImport } from './routes/_authenticated/app.reclamos'
import { Route as AuthenticatedAppReservasRouteImport } from './routes/_authenticated/app.reservas'
import { Route as AuthenticatedAppPagoReferenciaRouteImport } from './routes/_authenticated/app.pago.$referencia'
import { Route as ApiPublicWebhooksPagosMercadopagoRouteImport } from './routes/api/public/webhooks/pagos.mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlataformaRoute = AuthenticatedPlataformaRouteImport.update({
  id: '/plataforma',
  path: '/plataforma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAvisosRoute =
  AuthenticatedAdminAvisosRouteImport.update({
    id: '/avisos',
    path: '/avisos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConversacionesRoute =
  AuthenticatedAdminConversacionesRouteImport.update({
    id: '/conversaciones',
    path: '/conversaciones',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentosRoute =
  AuthenticatedAdminDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExpensasRoute =
  AuthenticatedAdminExpensasRouteImport.update({
    id: '/expensas',
    path: '/expensas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPersonasRoute =
  AuthenticatedAdminPersonasRouteImport.update({
    id: '/personas',
    path: '/personas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProveedoresRoute =
  AuthenticatedAdminProveedoresRouteImport.update({
    id: '/proveedores',
    path: '/proveedores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReclamosRoute =
  AuthenticatedAdminReclamosRouteImport.update({
    id: '/reclamos',
    path: '/reclamos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAsambleasRoute =
  AuthenticatedAppAsambleasRouteImport.update({
    id: '/asambleas',
    path: '/asambleas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAsistenteRoute =
  AuthenticatedAppAsistenteRouteImport.update({
    id: '/asistente',
    path: '/asistente',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAvisosRoute = AuthenticatedAppAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppContactoRoute =
  AuthenticatedAppContactoRouteImport.update({
    id: '/contacto',
    path: '/contacto',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentosRoute =
  AuthenticatedAppDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppExpensasRoute =
  AuthenticatedAppExpensasRouteImport.update({
    id: '/expensas',
    path: '/expensas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMudanzasRoute =
  AuthenticatedAppMudanzasRouteImport.update({
    id: '/mudanzas',
    path: '/mudanzas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReclamosRoute =
  AuthenticatedAppReclamosRouteImport.update({
    id: '/reclamos',
    path: '/reclamos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReservasRoute =
  AuthenticatedAppReservasRouteImport.update({
    id: '/reservas',
    path: '/reservas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPagoReferenciaRoute =
  AuthenticatedAppPagoReferenciaRouteImport.update({
    id: '/pago/$referencia',
    path: '/pago/$referencia',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicWebhooksPagosMercadopagoRoute =
  ApiPublicWebhooksPagosMercadopagoRouteImport.update({
    id: '/api/public/webhooks/pagos/mercadopago',
    path: '/api/public/webhooks/pagos/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/plataforma': typeof AuthenticatedPlataformaRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/avisos': typeof AuthenticatedAdminAvisosRoute
  '/admin/conversaciones': typeof AuthenticatedAdminConversacionesRoute
  '/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
  '/admin/expensas': typeof AuthenticatedAdminExpensasRoute
  '/admin/personas': typeof AuthenticatedAdminPersonasRoute
  '/admin/proveedores': typeof AuthenticatedAdminProveedoresRoute
  '/admin/reclamos': typeof AuthenticatedAdminReclamosRoute
  '/app/asambleas': typeof AuthenticatedAppAsambleasRoute
  '/app/asistente': typeof AuthenticatedAppAsistenteRoute
  '/app/avisos': typeof AuthenticatedAppAvisosRoute
  '/app/contacto': typeof AuthenticatedAppContactoRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/expensas': typeof AuthenticatedAppExpensasRoute
  '/app/mudanzas': typeof AuthenticatedAppMudanzasRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/reclamos': typeof AuthenticatedAppReclamosRoute
  '/app/reservas': typeof AuthenticatedAppReservasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/pago/$referencia': typeof AuthenticatedAppPagoReferenciaRoute
  '/api/public/webhooks/pagos/mercadopago': typeof ApiPublicWebhooksPagosMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/plataforma': typeof AuthenticatedPlataformaRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/avisos': typeof AuthenticatedAdminAvisosRoute
  '/admin/conversaciones': typeof AuthenticatedAdminConversacionesRoute
  '/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
  '/admin/expensas': typeof AuthenticatedAdminExpensasRoute
  '/admin/personas': typeof AuthenticatedAdminPersonasRoute
  '/admin/proveedores': typeof AuthenticatedAdminProveedoresRoute
  '/admin/reclamos': typeof AuthenticatedAdminReclamosRoute
  '/app/asambleas': typeof AuthenticatedAppAsambleasRoute
  '/app/asistente': typeof AuthenticatedAppAsistenteRoute
  '/app/avisos': typeof AuthenticatedAppAvisosRoute
  '/app/contacto': typeof AuthenticatedAppContactoRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/expensas': typeof AuthenticatedAppExpensasRoute
  '/app/mudanzas': typeof AuthenticatedAppMudanzasRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/reclamos': typeof AuthenticatedAppReclamosRoute
  '/app/reservas': typeof AuthenticatedAppReservasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/pago/$referencia': typeof AuthenticatedAppPagoReferenciaRoute
  '/api/public/webhooks/pagos/mercadopago': typeof ApiPublicWebhooksPagosMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/plataforma': typeof AuthenticatedPlataformaRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/avisos': typeof AuthenticatedAdminAvisosRoute
  '/_authenticated/admin/conversaciones': typeof AuthenticatedAdminConversacionesRoute
  '/_authenticated/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
  '/_authenticated/admin/expensas': typeof AuthenticatedAdminExpensasRoute
  '/_authenticated/admin/personas': typeof AuthenticatedAdminPersonasRoute
  '/_authenticated/admin/proveedores': typeof AuthenticatedAdminProveedoresRoute
  '/_authenticated/admin/reclamos': typeof AuthenticatedAdminReclamosRoute
  '/_authenticated/app/asambleas': typeof AuthenticatedAppAsambleasRoute
  '/_authenticated/app/asistente': typeof AuthenticatedAppAsistenteRoute
  '/_authenticated/app/avisos': typeof AuthenticatedAppAvisosRoute
  '/_authenticated/app/contacto': typeof AuthenticatedAppContactoRoute
  '/_authenticated/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/_authenticated/app/expensas': typeof AuthenticatedAppExpensasRoute
  '/_authenticated/app/mudanzas': typeof AuthenticatedAppMudanzasRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/reclamos': typeof AuthenticatedAppReclamosRoute
  '/_authenticated/app/reservas': typeof AuthenticatedAppReservasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/pago/$referencia': typeof AuthenticatedAppPagoReferenciaRoute
  '/api/public/webhooks/pagos/mercadopago': typeof ApiPublicWebhooksPagosMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/app'
    | '/plataforma'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/avisos'
    | '/admin/conversaciones'
    | '/admin/documentos'
    | '/admin/expensas'
    | '/admin/personas'
    | '/admin/proveedores'
    | '/admin/reclamos'
    | '/app/asambleas'
    | '/app/asistente'
    | '/app/avisos'
    | '/app/contacto'
    | '/app/documentos'
    | '/app/expensas'
    | '/app/mudanzas'
    | '/app/perfil'
    | '/app/reclamos'
    | '/app/reservas'
    | '/admin/'
    | '/app/'
    | '/app/pago/$referencia'
    | '/api/public/webhooks/pagos/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/plataforma'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/avisos'
    | '/admin/conversaciones'
    | '/admin/documentos'
    | '/admin/expensas'
    | '/admin/personas'
    | '/admin/proveedores'
    | '/admin/reclamos'
    | '/app/asambleas'
    | '/app/asistente'
    | '/app/avisos'
    | '/app/contacto'
    | '/app/documentos'
    | '/app/expensas'
    | '/app/mudanzas'
    | '/app/perfil'
    | '/app/reclamos'
    | '/app/reservas'
    | '/admin'
    | '/app'
    | '/app/pago/$referencia'
    | '/api/public/webhooks/pagos/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/plataforma'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/avisos'
    | '/_authenticated/admin/conversaciones'
    | '/_authenticated/admin/documentos'
    | '/_authenticated/admin/expensas'
    | '/_authenticated/admin/personas'
    | '/_authenticated/admin/proveedores'
    | '/_authenticated/admin/reclamos'
    | '/_authenticated/app/asambleas'
    | '/_authenticated/app/asistente'
    | '/_authenticated/app/avisos'
    | '/_authenticated/app/contacto'
    | '/_authenticated/app/documentos'
    | '/_authenticated/app/expensas'
    | '/_authenticated/app/mudanzas'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/reclamos'
    | '/_authenticated/app/reservas'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/app/pago/$referencia'
    | '/api/public/webhooks/pagos/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicWebhooksPagosMercadopagoRoute: typeof ApiPublicWebhooksPagosMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plataforma': {
      id: '/_authenticated/plataforma'
      path: '/plataforma'
      fullPath: '/plataforma'
      preLoaderRoute: typeof AuthenticatedPlataformaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/avisos': {
      id: '/_authenticated/admin/avisos'
      path: '/avisos'
      fullPath: '/admin/avisos'
      preLoaderRoute: typeof AuthenticatedAdminAvisosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/conversaciones': {
      id: '/_authenticated/admin/conversaciones'
      path: '/conversaciones'
      fullPath: '/admin/conversaciones'
      preLoaderRoute: typeof AuthenticatedAdminConversacionesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documentos': {
      id: '/_authenticated/admin/documentos'
      path: '/documentos'
      fullPath: '/admin/documentos'
      preLoaderRoute: typeof AuthenticatedAdminDocumentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/expensas': {
      id: '/_authenticated/admin/expensas'
      path: '/expensas'
      fullPath: '/admin/expensas'
      preLoaderRoute: typeof AuthenticatedAdminExpensasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/personas': {
      id: '/_authenticated/admin/personas'
      path: '/personas'
      fullPath: '/admin/personas'
      preLoaderRoute: typeof AuthenticatedAdminPersonasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/proveedores': {
      id: '/_authenticated/admin/proveedores'
      path: '/proveedores'
      fullPath: '/admin/proveedores'
      preLoaderRoute: typeof AuthenticatedAdminProveedoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reclamos': {
      id: '/_authenticated/admin/reclamos'
      path: '/reclamos'
      fullPath: '/admin/reclamos'
      preLoaderRoute: typeof AuthenticatedAdminReclamosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/asambleas': {
      id: '/_authenticated/app/asambleas'
      path: '/asambleas'
      fullPath: '/app/asambleas'
      preLoaderRoute: typeof AuthenticatedAppAsambleasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/asistente': {
      id: '/_authenticated/app/asistente'
      path: '/asistente'
      fullPath: '/app/asistente'
      preLoaderRoute: typeof AuthenticatedAppAsistenteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/avisos': {
      id: '/_authenticated/app/avisos'
      path: '/avisos'
      fullPath: '/app/avisos'
      preLoaderRoute: typeof AuthenticatedAppAvisosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contacto': {
      id: '/_authenticated/app/contacto'
      path: '/contacto'
      fullPath: '/app/contacto'
      preLoaderRoute: typeof AuthenticatedAppContactoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documentos': {
      id: '/_authenticated/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AuthenticatedAppDocumentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/expensas': {
      id: '/_authenticated/app/expensas'
      path: '/expensas'
      fullPath: '/app/expensas'
      preLoaderRoute: typeof AuthenticatedAppExpensasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/mudanzas': {
      id: '/_authenticated/app/mudanzas'
      path: '/mudanzas'
      fullPath: '/app/mudanzas'
      preLoaderRoute: typeof AuthenticatedAppMudanzasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reclamos': {
      id: '/_authenticated/app/reclamos'
      path: '/reclamos'
      fullPath: '/app/reclamos'
      preLoaderRoute: typeof AuthenticatedAppReclamosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reservas': {
      id: '/_authenticated/app/reservas'
      path: '/reservas'
      fullPath: '/app/reservas'
      preLoaderRoute: typeof AuthenticatedAppReservasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pago/$referencia': {
      id: '/_authenticated/app/pago/$referencia'
      path: '/pago/$referencia'
      fullPath: '/app/pago/$referencia'
      preLoaderRoute: typeof AuthenticatedAppPagoReferenciaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/webhooks/pagos/mercadopago': {
      id: '/api/public/webhooks/pagos/mercadopago'
      path: '/api/public/webhooks/pagos/mercadopago'
      fullPath: '/api/public/webhooks/pagos/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksPagosMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAvisosRoute: typeof AuthenticatedAdminAvisosRoute
  AuthenticatedAdminConversacionesRoute: typeof AuthenticatedAdminConversacionesRoute
  AuthenticatedAdminDocumentosRoute: typeof AuthenticatedAdminDocumentosRoute
  AuthenticatedAdminExpensasRoute: typeof AuthenticatedAdminExpensasRoute
  AuthenticatedAdminPersonasRoute: typeof AuthenticatedAdminPersonasRoute
  AuthenticatedAdminProveedoresRoute: typeof AuthenticatedAdminProveedoresRoute
  AuthenticatedAdminReclamosRoute: typeof AuthenticatedAdminReclamosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAvisosRoute: AuthenticatedAdminAvisosRoute,
  AuthenticatedAdminConversacionesRoute: AuthenticatedAdminConversacionesRoute,
  AuthenticatedAdminDocumentosRoute: AuthenticatedAdminDocumentosRoute,
  AuthenticatedAdminExpensasRoute: AuthenticatedAdminExpensasRoute,
  AuthenticatedAdminPersonasRoute: AuthenticatedAdminPersonasRoute,
  AuthenticatedAdminProveedoresRoute: AuthenticatedAdminProveedoresRoute,
  AuthenticatedAdminReclamosRoute: AuthenticatedAdminReclamosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAsambleasRoute: typeof AuthenticatedAppAsambleasRoute
  AuthenticatedAppAsistenteRoute: typeof AuthenticatedAppAsistenteRoute
  AuthenticatedAppAvisosRoute: typeof AuthenticatedAppAvisosRoute
  AuthenticatedAppContactoRoute: typeof AuthenticatedAppContactoRoute
  AuthenticatedAppDocumentosRoute: typeof AuthenticatedAppDocumentosRoute
  AuthenticatedAppExpensasRoute: typeof AuthenticatedAppExpensasRoute
  AuthenticatedAppMudanzasRoute: typeof AuthenticatedAppMudanzasRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppReclamosRoute: typeof AuthenticatedAppReclamosRoute
  AuthenticatedAppReservasRoute: typeof AuthenticatedAppReservasRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppPagoReferenciaRoute: typeof AuthenticatedAppPagoReferenciaRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAsambleasRoute: AuthenticatedAppAsambleasRoute,
  AuthenticatedAppAsistenteRoute: AuthenticatedAppAsistenteRoute,
  AuthenticatedAppAvisosRoute: AuthenticatedAppAvisosRoute,
  AuthenticatedAppContactoRoute: AuthenticatedAppContactoRoute,
  AuthenticatedAppDocumentosRoute: AuthenticatedAppDocumentosRoute,
  AuthenticatedAppExpensasRoute: AuthenticatedAppExpensasRoute,
  AuthenticatedAppMudanzasRoute: AuthenticatedAppMudanzasRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppReclamosRoute: AuthenticatedAppReclamosRoute,
  AuthenticatedAppReservasRoute: AuthenticatedAppReservasRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppPagoReferenciaRoute: AuthenticatedAppPagoReferenciaRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedPlataformaRoute: typeof AuthenticatedPlataformaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedPlataformaRoute: AuthenticatedPlataformaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicWebhooksPagosMercadopagoRoute:
    ApiPublicWebhooksPagosMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
